spring:
  application:
    name: sonar-repositories
  data:
    mongodb:
      database: repos
      uri: ${URI_DATABASE_CONNECTION:mongodb://localhost}
      keepAlive: 120000
      autoConnectRetry: true
      socketTimeOut: 60000
      connectTimeout: 60000
      socketKeepAlive: true
      auto-index-creation: true
server:
  port: ${PORT:0}
  http2:
    enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${DEFAULTZONE_EUREKA_CONNECTION:http://localhost:8761/eureka}
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      database: repos
      uri: mongodb://localhost
server:
  port: 8080
eureka:
  client:
    enabled: false